### ISSUE TITLE
Error in Ubuntu 16.04 (Meteor 1.3.5.1):

### ISSUE THREAD

**Issue by Rongky** [risetechnologies/meteor-electron-builder#13]
I'm having this error when using the package in Ubuntu 16.04 (Meteor 1.3.5.1):

/home/user/myproject/.meteor/local/build/programs/server/packages/risetechnologies_electron-builder.js:559
const path = require("path");
^^^^^

SyntaxError: Use of const in strict mode.
at home/user/myproject/web/.meteor/local/build/programs/server/boot.js:292:30
at Array.forEach (native)
at Function..each..forEach (/home/user/.meteor/packages/meteor-tool/.1.3.5_1.u2i7oe++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
at /home/user/myproject/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8

**Comment by menelike** [comment]
thanks @Rongky , I'll take care of this within the next days. 

Is it possible to test this against Meteor 1.4.x ?
This might be related to the older npm version in Meteor 1.3.x (http://stackoverflow.com/a/35218558/1981426)

**Comment by Rongky** [comment]
thanks for the quick reply. 
after testing against meteor 1.4.2, below is the new error:

Error: Cannot find module '7zip-bin-linux'
     at Function.Module._resolveFilename (module.js:325:15)
     at Function.Module._load (module.js:276:25)
     at Module.require (module.js:353:17)
     at require (internal/module.js:12:17)
     at Object.<anonymous> (/home/user/.meteor/packages/risetechnologies_electron-builder/.0.1.3.7mqerq++os+web.browser+web.cordova/npm/node_modules/7zip-bin/index.js:13:67)
     at Module._compile (module.js:409:26)
     at Object.Module._extensions..js (module.js:416:10)
     at Module.load (module.js:343:32)
     at Function.Module._load (module.js:300:12)
     at Module.require (module.js:353:17)
     at require (internal/module.js:12:17)
     at Object.<anonymous> (/home/user/.meteor/packages/risetechnologies_electron-builder/.0.1.3.7mqerq++os+web.browser+web.cordova/npm/node_modules/electron-builder/src/targets/archive.ts:5:1)
     at Module._compile (module.js:409:26)
     at Object.Module._extensions..js (module.js:416:10)
     at Module.load (module.js:343:32)
     at Function.Module._load (module.js:300:12)
 
tried to install npm package 7zip-bin-linux both locally and globally, still the same error.
my production app is still at meteor 1.3.5.1 due to deployment issues with mup.

I'm really looking forward in deploying a desktop version of the app using your package since
it is the only one with a linux build capabilities.

Thanks very much for this package.

**Comment by menelike** [comment]
closing this, since we're gonna support Meteor >= 1.4, I highly recommend https://github.com/wojtkowiak/meteor-desktop as an more up to date and maintained solution.
