### ISSUE TITLE
test functionality in linux

### ISSUE THREAD

**Issue by menelike** [risetechnologies/meteor-electron-builder#6]

**Comment by Rongky** [comment]
I'm having this error when using the package in Ubuntu 16.04 (Meteor 1.3.5.1):

/home/user/myproject/.meteor/local/build/programs/server/packages/risetechnologies_electron-builder.js:559
const path = require("path");
^^^^^     
SyntaxError: Use of const in strict mode.
     at home/user/myproject/web/.meteor/local/build/programs/server/boot.js:292:30
     at Array.forEach (native)
     at Function._.each._.forEach (/home/user/.meteor/packages/meteor-tool/.1.3.5_1.u2i7oe++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
     at /home/user/myproject/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8

**Comment by menelike** [comment]
thanks @Rongky , I'll take care of this within the next days. 

Is it possible to test this against Meteor 1.4.x ?
This might be related to the older npm version in Meteor 1.3.x (http://stackoverflow.com/a/35218558/1981426)
